// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:finasstech/core/database/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BudgetCategoryModelAdapter());
    registerAdapter(BudgetModelAdapter());
    registerAdapter(ExpenseModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}
